[project]
name = 'Decentralized-Rare-Disease-Data-Sharing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.condition-tracking]
path = 'contracts/condition-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.patient-anonymization]
path = 'contracts/patient-anonymization.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-access]
path = 'contracts/research-access.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
